// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.
#pragma once

#include <frc2/command/SubsystemBase.h>
#include "ctre/Phoenix.h"
#include <frc/Encoder.h>
#include <rev/CANSparkMax.h>
#include "subsystems/SwervePod.h"
#include <frc/kinematics/SwerveDriveKinematics.h>
#include <units/velocity.h>

#define FRONT_RIGHT  0
#define FRONT_LEFT  1
#define BACK_RIGHT  2
#define BACK_LEFT  3

#define k_DB (double)0.07
/**
 * SwerveDrive header file
 *
 * @author 2826WaveRobotics
 */
class SwerveDrive: public frc2::SubsystemBase {
    // It's desirable that everything possible is private except
    // for methods that implement subsystem capabilities
    private:        

        rev::CANSparkMax *m_frontBottomMotor;
        rev::CANSparkMax *m_frontTopMotor;
        rev::CANSparkMax *m_rearBottomMotor;
        rev::CANSparkMax *m_rearTopMotor;

        rev::SparkMaxRelativeEncoder *m_topEncoder;
        rev::SparkMaxRelativeEncoder *m_bottomEncoder;

        // rev::CANSparkMax *m_rightFrontBottomMotor;
        // rev::CANSparkMax *m_rightFrontTopMotor;
        // rev::CANSparkMax *m_rightBackBottomMotor;
        // rev::CANSparkMax *m_rightBackTopMotor;
        // rev::CANSparkMax *m_leftBackBottomMotor;
        // rev::CANSparkMax *m_leftBackTopMotor;

        // frc::SwerveDriveKinematics<3> *m_kinematics;

        frc::SwerveDriveKinematics<2> *m_kinematics;

        SwervePod *m_frontPod;
        SwervePod *m_rearPod;
        //SwervePod *m_frontRightPod;
        //SwervePod *m_backLeftPod;
        //SwervePod *m_backRightPod;             

    public:
        SwerveDrive();

        void Periodic() override;
        void SimulationPeriodic() override;

        // This is meant to take in inputs from the joysticks
        void DrivePods(double forward, double strafe, double rotation);

        void initialize();
        
};

