// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

#pragma once

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <frc/smartdashboard/SendableChooser.h>
#include <frc2/command/Command.h>
#include <frc/XboxController.h>

#include "subsystems/SwerveDrive.h"

#include "commands/AutonomousCommand.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

class RobotContainer {

public:

    frc2::Command* GetAutonomousCommand();
    static RobotContainer* GetInstance();

    // The robot's subsystems
    SwerveDrive m_swerveDrive;

    // Controller input
    frc::XboxController* getDriver();
    frc::XboxController* getOperator();

private:

    RobotContainer();

    //static RobotContainer s_robotContainer;
    static RobotContainer* m_robotContainer;

    // controllers assigned ports
    frc::XboxController m_driver{0};
    frc::XboxController m_operator{1};    

    frc::SendableChooser<frc2::Command*> m_chooser;
    AutonomousCommand m_autonomousCommand;    
    void ConfigureButtonBindings();
};